---
name: "Thunder Subtitles"
guid: "e4ce9da9-ef00-417c-96f2-861c512d45eb"
version: "1.0.4.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Download subtitles from Thunder XMP"
description: >
  Download subtitles from Thunder XMP.
  https://github.com/jjm2473/jellyfin-plugin-thundersub
  original source https://github.com/91270/Emby.MeiamSub
category: "Metadata"
owner: "jjm2473"
artifacts:
- "Jellyfin.MeiamSub.Thunder.dll"
changelog: >
  https://github.com/91270/Emby.MeiamSub/commit/492294941f822595446fedcf268f4117dacebc1c
