name: Build Plugin 10.7

on:
  push:
    branches: [ 10.7 ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ 10.7 ]
    paths-ignore:
      - '**/*.md'

jobs:
  build_10_7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build Jellyfin Plugin
        uses: oddstr13/jellyfin-plugin-repository-manager@v0.4.2
        id: jprm
        with:
            dotnet-target: net5.0

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          retention-days: 30
          if-no-files-found: error
          path: ${{ steps.jprm.outputs.artifact }}
